### ISSUE TITLE
Гипотеза о отсутствии корреляционной зависимости

### ISSUE THREAD

**Issue by Ygenks** [budnyjj/stat#1]
В формуле расчёта критерия, распределенного по нормальному закону (n>= 50) есть косяк.
В знаменателе дроби (117 строка) не должен стоять корень.

**Comment by budnyjj** [comment]
Привет. Укажи, пожалуйста, точное местонаждение проблемы... а то я уже не помню толком, что тут к чему было :)

**Comment by budnyjj** [comment]
Или сделай pull request с исправлением.
